[build-system]
requires = [
    "setuptools>=83.0.0",
    "wheel>=0.47.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "texas"
version = "0.15.1"
description = ""
requires-python = ">=3.12"
authors = [
    { name = "Helmut Konrad Schewe", email = "helmutus@outlook.com" },
]
dependencies = [
    "utilo>=2.109.1,<3.0.0",
    "iamraw>=4.93.0,<5.0.0",
    "germania>=1.32.1,<2.0.0",
    "verbo>=1.23.4,<2.0.0",
    "configos>=1.0.4,<2.0.0",
    "bibliographia>=1.0.1,<2.0.0",
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.readme]
file = "README"
content-type = "text/markdown"

[project.optional-dependencies]
dev = [
    "utilotest==1.0.5",
    "hoverpower==1.6.0",
    "rawmaker==2.40.5",
    "gennex==1.1.0",
    "titulum==1.0.2",
    "indicibus==1.0.2",
]

[project.urls]
Homepage = "https://github.com/anaticulae/texas"
Repository = "https://github.com/anaticulae/texas"

[project.scripts]
docref = "docref.cli:main"
textflow = "textflow.cli:main"
weblink = "weblink.cli:main"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

[tool.semantic_release.changelog]
mode = "init"
output_format = "md"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG"

[tool.semantic_release.commit_parser_options]
patch_tags = [
    "build",
    "chore",
    "ci",
    "deps",
    "docs",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = [
    "feat",
]

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "docref",
    "docref.biblio",
    "docref.biblio.strategies",
    "docref.features",
    "texas",
    "textflow",
    "textflow.alignment",
    "textflow.features",
    "weblink",
    "weblink.features",
]
exclude = [
    "tests*",
]

[tool.hoverpower]
packages = [
    "BACHELOR",
    "BOOK",
    "DISS",
    "DOCU",
    "HOME",
    "MASTER",
    "ORDER",
    "PAPER",
]
